### 1. Load Library

In [26]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer, SimpleImputer

### 2. Load Dataset

In [23]:
df = pd.DataFrame(
    {
        "usia": [25, 30, np.nan, np.nan, 22],
        "gaji": [5000000, np.nan, 7000000, 12000000, 4500000],
        "kota": ["Jakarta", "Bandung", np.nan, "Jakarta", "Surabaya"],
    }
)
df.head()

   usia        gaji      kota
0  25.0   5000000.0   Jakarta
1  30.0         NaN   Bandung
2   NaN   7000000.0       NaN
3   NaN  12000000.0   Jakarta
4  22.0   4500000.0  Surabaya

### 3.1. Check Missing Value

In [24]:
df.isna().sum()

usia    2
gaji    1
kota    1
dtype: int64

### 3.2 Hapus Missing Value Value

In [25]:
df_drop = df.dropna()
df_drop

   usia       gaji      kota
0  25.0  5000000.0   Jakarta
4  22.0  4500000.0  Surabaya

### 3.3. Median untuk numerik

In [27]:
imputer_num = SimpleImputer(strategy="median")
df["usia"] = imputer_num.fit_transform(df[["usia"]])
df

   usia        gaji      kota
0  25.0   5000000.0   Jakarta
1  30.0         NaN   Bandung
2  25.0   7000000.0       NaN
3  25.0  12000000.0   Jakarta
4  22.0   4500000.0  Surabaya

### 3.4. Imputation Prediktif

In [28]:
knn_imp = KNNImputer(n_neighbors=2)
df_knn = df
df_knn[["usia", "gaji"]] = knn_imp.fit_transform(df_knn[["usia", "gaji"]])
df_knn

   usia        gaji      kota
0  25.0   5000000.0   Jakarta
1  30.0   6000000.0   Bandung
2  25.0   7000000.0       NaN
3  25.0  12000000.0   Jakarta
4  22.0   4500000.0  Surabaya