### 1. Load Library

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

### 2. Load Dataset

In [2]:
data = {
    "usia": [20, 25, 30, 45, 50],  # Rentang puluhan
    "gaji": [
        3_000_000,
        5_000_000,
        8_000_000,
        15_000_000,
        25_000_000,
    ],  # Rentang jutaan
}
df = pd.DataFrame(data)
df

   usia      gaji
0    20   3000000
1    25   5000000
2    30   8000000
3    45  15000000
4    50  25000000

### 3.1. Min-Max Normalization (Skala [0, 1])

In [9]:
minmax_scaler = MinMaxScaler()
df_minmax = pd.DataFrame(
    minmax_scaler.fit_transform(df),
    columns=["usia_minmax", "gaji_minmax"],
)
df_minmax = pd.concat([df, df_minmax], axis=1)
df_minmax

   usia      gaji  usia_minmax  gaji_minmax
0    20   3000000     0.000000     0.000000
1    25   5000000     0.166667     0.090909
2    30   8000000     0.333333     0.227273
3    45  15000000     0.833333     0.545455
4    50  25000000     1.000000     1.000000

### 3.2. Standardization / Z-Score (Mean = 0, Std = 1)

In [10]:
std_scaler = StandardScaler()
df_std = pd.DataFrame(
    std_scaler.fit_transform(df),
    columns=["usia_zscore", "gaji_zscore"],
)
df_std = pd.concat([df, df_std], axis=1)
df_std

   usia      gaji  usia_zscore  gaji_zscore
0    20   3000000    -1.209416    -1.023721
1    25   5000000    -0.777482    -0.774033
2    30   8000000    -0.345547    -0.399501
3    45  15000000     0.950255     0.474407
4    50  25000000     1.382189     1.722848